################################################
# this file is created by me                   #
# to inherete the file generated by pyside-uic #
################################################

from PySide6.QtWidgets import QMainWindow
from ui_mainwindow import Ui_MainWindow
import note_management as noteManager

class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.setWindowTitle("NoteBook v2.0")
        self.printNotes()
        self.lineEdit.setText("Type your new note here")
        self.listWidget.itemSelectionChanged.connect(self.onItemSelectionChanged)

        ### button signals and slots connections ##################################
        self.newButton.clicked.connect(lambda: noteManager.newAction(self))       #
        self.doneButton.clicked.connect(lambda:noteManager.doneAction(self))      #
        self.editButton.clicked.connect(lambda: noteManager.editAction(self))     #
        self.deleteButton.clicked.connect(lambda: noteManager.deleteAction(self)) #
        self.exitButton.clicked.connect(noteManager.exitAction)                   #
        ###########################################################################

        #self.listWidget.

    def printNotes(self):
        self.listWidget.clear()
        noteIndex = 1
        for notes in noteManager.noteList:
            notes = str(noteIndex) + ") " + notes
            self.listWidget.addItem(notes)
            noteIndex = noteIndex + 1

    def onItemSelectionChanged(self):
        self.newButton.setEnabled(False)
        self.doneButton.setEnabled(True)
        self.editButton.setEnabled(True)
        self.deleteButton.setEnabled(True)

    def resetButtonStates(self):
        self.newButton.setEnabled(True)
        self.doneButton.setEnabled(False)
        self.editButton.setEnabled(False)
        self.deleteButton.setEnabled(False)