################################################
# this file is created by me                   #
# to inherete the file generated by pyside-uic #
################################################

from PySide6.QtWidgets import QMainWindow
from ui_mainwindow import Ui_MainWindow
import note_management as noteManager

class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.setWindowTitle("NoteBook v2.0")
        self.printNotes()

        ### button signals and slots connections ############################
        self.newButton.clicked.connect(lambda: noteManager.newAction(self)) #
        self.doneButton.clicked.connect(noteManager.doneAction)             #
        self.editButton.clicked.connect(lambda: noteManager.editAction(self))             #
        self.deleteButton.clicked.connect(lambda: noteManager.deleteAction(self))         #
        self.exitButton.clicked.connect(noteManager.exitAction)             #
        #####################################################################

    def printNotes(self):
        self.listWidget.clear()
        noteIndex = 1
        for notes in noteManager.noteList:
            notes = str(noteIndex) + ") " + notes
            self.listWidget.addItem(notes)
            noteIndex = noteIndex + 1